/**
 * k6 load test — JSONPlaceholder /posts endpoints
 *
 * Run locally:  k6 run performance/posts.k6.js
 * Run with summary output:  k6 run --out json=performance/results.json performance/posts.k6.js
 *
 * Thresholds (what a CI gate would enforce):
 *   - p95 response time < 500ms
 *   - error rate < 1%
 */

import http from 'k6/http';
import { check, sleep, group } from 'k6';
import { Rate, Trend, Counter } from 'k6/metrics';

// ─── Custom metrics ───────────────────────────────────────────────────────────

const errorRate = new Rate('error_rate');
const listPostsDuration = new Trend('list_posts_duration_ms', true);
const getPostDuration = new Trend('get_post_duration_ms', true);
const createPostDuration = new Trend('create_post_duration_ms', true);
const requestCount = new Counter('request_count');

// ─── Load profile ─────────────────────────────────────────────────────────────

export const options = {
  stages: [
    { duration: '30s', target: 10 },   // ramp up to 10 VUs
    { duration: '1m',  target: 10 },   // hold steady
    { duration: '30s', target: 25 },   // spike to 25 VUs
    { duration: '30s', target: 10 },   // back to 10
    { duration: '15s', target: 0 },    // ramp down
  ],
  thresholds: {
    http_req_duration:     ['p(95)<500', 'p(99)<1000'],
    http_req_failed:       ['rate<0.01'],
    error_rate:            ['rate<0.01'],
    list_posts_duration_ms:  ['p(95)<600'],
    get_post_duration_ms:    ['p(95)<400'],
    create_post_duration_ms: ['p(95)<700'],
  },
};

const BASE = 'https://jsonplaceholder.typicode.com';

const JSON_HEADERS = { 'Content-Type': 'application/json' };

// ─── Main VU script ───────────────────────────────────────────────────────────

export default function () {
  group('GET /posts (list)', () => {
    const res = http.get(`${BASE}/posts`);
    requestCount.add(1);
    listPostsDuration.add(res.timings.duration);

    const ok = check(res, {
      'status 200':         (r) => r.status === 200,
      'returns 100 posts':  (r) => JSON.parse(r.body).length === 100,
      'p95 < 500ms':        (r) => r.timings.duration < 500,
    });
    errorRate.add(!ok);
  });

  sleep(1);

  group('GET /posts/:id (single resource)', () => {
    const id = Math.floor(Math.random() * 100) + 1;
    const res = http.get(`${BASE}/posts/${id}`);
    requestCount.add(1);
    getPostDuration.add(res.timings.duration);

    const body = JSON.parse(res.body);
    const ok = check(res, {
      'status 200':          (r) => r.status === 200,
      'correct id returned': () => body.id === id,
      'has title':           () => typeof body.title === 'string' && body.title.length > 0,
      'p95 < 400ms':         (r) => r.timings.duration < 400,
    });
    errorRate.add(!ok);
  });

  sleep(1);

  group('POST /posts (create)', () => {
    const payload = JSON.stringify({
      userId: Math.floor(Math.random() * 10) + 1,
      title: `Load test post ${Date.now()}`,
      body: 'Generated by k6 load test',
    });

    const res = http.post(`${BASE}/posts`, payload, { headers: JSON_HEADERS });
    requestCount.add(1);
    createPostDuration.add(res.timings.duration);

    const body = JSON.parse(res.body);
    const ok = check(res, {
      'status 201':        (r) => r.status === 201,
      'id assigned':       () => typeof body.id === 'number',
      'title echoed back': () => body.title.startsWith('Load test post'),
      'p95 < 700ms':       (r) => r.timings.duration < 700,
    });
    errorRate.add(!ok);
  });

  sleep(1);
}

// ─── Summary output ───────────────────────────────────────────────────────────

export function handleSummary(data) {
  return {
    stdout: buildSummary(data),
  };
}

function buildSummary(data) {
  const m = data.metrics;
  const p95 = (metric) => metric?.values?.['p(95)']?.toFixed(0) ?? 'n/a';
  const rate = (metric) => ((metric?.values?.rate ?? 0) * 100).toFixed(2);

  return `
╔══════════════════════════════════════════════════════╗
║            k6 Load Test — JSONPlaceholder            ║
╚══════════════════════════════════════════════════════╝

Requests total : ${m.request_count?.values?.count ?? 0}
Error rate     : ${rate(m.error_rate)}% (threshold <1%)

Endpoint p95 response times:
  GET /posts (list)   ${p95(m.list_posts_duration_ms)} ms  (threshold <600ms)
  GET /posts/:id      ${p95(m.get_post_duration_ms)} ms  (threshold <400ms)
  POST /posts         ${p95(m.create_post_duration_ms)} ms  (threshold <700ms)

Overall p95 : ${p95(m.http_req_duration)} ms
Overall p99 : ${(m.http_req_duration?.values?.['p(99)'] ?? 0).toFixed(0)} ms
`;
}
